# Generated by Django 5.1.3 on 2025-01-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
